### ISSUE TITLE
The homepage should note that the app is basically public

### ISSUE THREAD

**Issue by louiseswift** [no-mayo/today-i-learned#19]
We don't have any clear data privacy policy, so best to let people know that it's currently a demo/test app so they shouldn't enter any private data.

A basic note on the homepage (in the footer?) should do - unless anyone has an alternative preference.

(See separate issue for allowing users to delete their accounts to destroy any saved user data.)

**Comment by OlenaKashuba** [comment]
@louiseswift Hello, I am into working on this issue. I just wonder if you are happy with the note "This is a test app, please, do not enter any private data" in the footer?

**Comment by louiseswift** [comment]
@OlenaKashuba yes - that sounds perfect, thank you.
